#!/usr/bin/env bash

echo $MILSON_USER
echo $MILSON_PASSWORD
echo $MILSON_DBNAME

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER  $MILSON_USER WITH PASSWORD '$MILSON_PASSWORD';
    ALTER ROLE $MILSON_USER superuser;
    CREATE DATABASE $MILSON_DBNAME;
    ALTER DATABASE $MILSON_DBNAME OWNER TO $MILSON_USER;
    GRANT ALL PRIVILEGES ON DATABASE $MILSON_DBNAME to $MILSON_USER
EOSQL

psql -v --username "$POSTGRES_USER" -d  $MILSON_DBNAME  <<-EOSQL
    ALTER SCHEMA public OWNER TO $MILSON_USER;
EOSQL



